### ISSUE TITLE
Fullscreen background video

### ISSUE THREAD

**Issue by yschiangg** [yschiangg/dct_f#3]
I, V, VI, VIII&9b are supposed to have fullscreen videos as background.
The current codes[ only work in firefox](https://i.imgur.com/2wVYpPV.png), [in chrome and others](https://i.imgur.com/nvAHzWs.png), the videos do not have the desired effect. 
(Or maybe I should just render all the videos in different sizes again?)

**Comment by abcdefgs0324** [comment]
Hi @suwenyu ,
She needs your help.

**Comment by suwenyu** [comment]
I can't understand. It works on my Chrome.

https://imgur.com/a/LUWflTf
