### ISSUE TITLE
Unwanted navigation bar

### ISSUE THREAD

**Issue by abcdefgs0324** [yschiangg/dct_f#4]
In V.html, credits.html, and about.html, there is an unwanted "Home" in the navigation bar which is not related to your pages.

**Comment by abcdefgs0324** [comment]
"Burger" appears when I click the navigation bar on some pages.
"link to next page" needs to be removed.

**Comment by yschiangg** [comment]
Will do the clean up once I get the last 3 pages done!

**Comment by abcdefgs0324** [comment]
I will close this issue because I think it doesn’t matter.
